### PR TITLE
Fix FetchContent

### PR DESCRIPTION
**Pull request by stigrj**
* Remove `GIT_SHALLOW 1` in MRCPP, XCFun and Getkw so that we can point to older revisions.
* Update MRCPP and Getkw to latest and greatest.

### CODE REVIEW

**Comment by stigrj** [comment]
Why does Circle always fail on the first try with MPI? :angry:

**Comment by robertodr** [comment]
Probably the threshold is too tight and MPI generates slightly non-deterministic results on the last digits?

**Comment by stigrj** [comment]
Oh wait, now it's actually a real error :slightly_smiling_face: But usually it's one integration test that times out in the first run, but works after restart.

**Comment by stigrj** [comment]
I'm rewinding to previous MRCPP, the latest version is not `numerically_exact` with different number of MPIs. I will address this problem in #204.

**Pull request merged**
