### PR TITLE
Prepare v1.0.1

### PR DESCRIPTION
**Pull request by stigrj**
Cherry-picks from `master`. From `CHANGELOG.md`:
### Changed

- Moved CI from Travis to GitHub Actions
- Abort on failure when reading MW guess

### Fixed

- Minor issues with the printed output
- Error in NMR tensor output (dia term printed transposed)
- Precision issue with CHK guess (now full world_prec is used)
- MPI dead-lock when mixing shared-mem potentials with orbital bank
- SAD guess for large systems (Eigen threading error in matrix multiply)
- CORE/SAD guess for heavy atoms (force refinement for sharp s-functions)

### CODE REVIEW

**Review by robertodr — APPROVED** [review]
Another release well done :champagne:

**Comment by stigrj** [comment]
Hmm, no CI on `release/*`?

**Comment by stigrj** [comment]
Or I just missed it? We used to wait 1h for Travis to finish...

**Comment by robertodr** [comment]
I think it ran. See the checks tab.

**Pull request merged**
