### PR TITLE
Third take on std 14

### PR DESCRIPTION
**Pull request by stigrj**

### CODE REVIEW

**Comment by stigrj** [comment]
Ok, I'm not able to make this work before christmas :santa:

**Comment by ilfreddy** [comment]
Happy Christmas to you too :-)

**Comment by robertodr** [comment]
Travis needs a newer compiler, at least GCC 4.9, I think

**Comment by robertodr** [comment]
The Docker image on CircleCI also needed an update (which I have pushed to Docker Hub) I cannot restart the builds though.

**Comment by stigrj** [comment]
Hmm, something happened with Circle on the latest rebase: `CMAKE_PROJECT_NAME` not in cache

**Comment by robertodr** [comment]
@stigrj see here: https://github.com/MRChemSoft/vampyr/pull/20#issuecomment-450866305 The Docker image has an old CMake :/

**Comment by stigrj** [comment]
I don't think anything is happening, the build has been pending for 40 min

**Comment by stigrj** [comment]
It worked when I cancelled and restarted the build at dockerhub

**Comment by robertodr** [comment]
Docker Hub can be quite slow at picking up builds...

**Pull request merged**
