### PR TITLE
[WIP] Fix path to getkw Python packages

### LINKED ISSUE #206: Preinstalled Getkw
The following copy paths are not correct when using a preinstalled `getkw`:
https://github.com/MRChemSoft/mrchem/blob/c67777a665e633a826913849d0db5b5ee2c6b078/cmake/custom/main.cmake#L10-L16

In particular, the `getkw_sources_BINARY_DIR` variable seems empty. There's also an error in the Python install path in `getkw` (https://github.com/dev-cafe/libgetkw/issues/30), but that's only half the issue.

### PR DESCRIPTION
**Pull request by stigrj**
Not sure this is the correct path to include from, but it works

### CODE REVIEW

**Comment by stigrj** [comment]
Noo, this does not work when `getkw` is fetched in the superbuild

**Comment by stigrj** [comment]
Ok, this works, but it feels dirty

**Comment by robertodr** [comment]
I think the CMake configuration module needs an update. I am not sure if I'll get the time today or later in the weekend, though.

**Comment by robertodr** [comment]
I think #210 supersedes this one (and it's less dirty :wink: )

**Comment by stigrj** [comment]
Fixed in #210

**Pull request closed without merging**
