### PR TITLE
Fix runtime failure while reading basis set for SAD guess

### PR DESCRIPTION
**Pull request by robertodr**
This somehow only manifests in the Conda package... Go figure! :man_shrugging:

### CODE REVIEW

**Comment by robertodr** [comment]
Please squash the history, the commit message are utterly silly!

**Comment by robertodr** [comment]
And the new version of Minazo doesn't work.

**Comment by robertodr** [comment]
Minazo has some issues running its checks. I can't debug it right now though.

**Comment by robertodr** [comment]
This one is ready. The bot fails for reasons unrelated to this PR and I can't manage to fix it.

**Review by stigrj — APPROVED** [review]
So does this solve the conda problem?

**Comment by robertodr** [comment]
Yes it does.

**Pull request merged**
