### PR TITLE
Update external to official MRCPP-1.2.0 and XCFun-2.0.0

### PR DESCRIPTION
**Pull request by stigrj**

### CODE REVIEW

**Comment by stigrj** [comment]
We get the following error in `debug`, reproduced on my laptop
```
make[2]: *** No rule to make target 'lib/libxcfun_d.so.2', needed by 'lib/libmrchem.so'.
```
@robertodr do you know where the "_d" comes from?

**Comment by robertodr** [comment]
It's the suffix appended for the debug version. It's not quite clear why it looks for the debug version when it's building it in release...

**Comment by stigrj** [comment]
I'm not able to locate this error. Should I just change back to debug build of XCFun, or do you want to have a go at it?

**Comment by robertodr** [comment]
I can have a look tomorrow.

**Comment by robertodr** [comment]
I cannot reproduce locally using your branch. I am building with `./setup --type=release`

**Comment by stigrj** [comment]
It's when building mrchem in debug while xcfun is release

**Comment by robertodr** [comment]
> It's when building mrchem in debug while xcfun is release

OK, I had completely misunderstood...

**Comment by robertodr** [comment]
I think the quickest is to remove the `DEBUG_POSTFIX` property from the `xcfun` target directly in the XCFun repo. I will release a v2.0.1 once I've tested it with MRChem.

**Comment by robertodr** [comment]
See dftlibs/xcfun#130

**Comment by stigrj** [comment]
Wow, that's a heavy blow on code coverage

**Comment by robertodr** [comment]
> Wow, that's a heavy blow on code coverage

How's that possible? :scream:

**Comment by stigrj** [comment]
Looks like _a lot_ of files were not included in the coverage before, and for some reason they were included now. I think we need a unit test hackathon

**Pull request merged**
