### PR TITLE
Less warnings when building the docs

### PR DESCRIPTION
**Pull request by Gabrielgerez**
This removes the warnings when building the documentation, but introduces a new one. 
I need to run `./makedoc.sh` twice for it to take effect though.

### CODE REVIEW

**Comment by robertodr** [comment]
Uhm... Why the need to run `makedoc.sh` twice? Can you post the new warning?

**Comment by Gabrielgerez** [comment]
> Uhm... Why the need to run `makedoc.sh` twice? Can you post the new warning?

I'm not too sure myself
Here is the warning. Note that if i fix this by adding the file to a toctree then there will appear a second warning.
```
reading sources... [100%] programmers/manual                                                                                                
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/ggerez/repos/mrchem/doc/programmers/programmers-manual.rst: WARNING: document isn't included in any toctree
/home/ggerez/repos/mrchem/doc/users/user_out.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] programmers/manual
generating indices...  genindexdone
writing additional pages...  searchdone
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 2 warnings.

The HTML pages are in doc/html.
```

**Comment by Gabrielgerez** [comment]
I got the fix from here:
https://stackoverflow.com/a/62643624/14213803

**Comment by stigrj** [comment]
The `programmers-manual` should _not_ be included. I think it was copied from somewhere else (PCMSolver?) with the plan to adapt it to our needs, but it has not yet been done

**Comment by Gabrielgerez** [comment]
Understood, will see if i can remove the warning for the time being then.

**Comment by Gabrielgerez** [comment]
All the warnings that are left now are wrong syntax for comments in the code. These do not show up red  and are not counted at the end of the build. 
I believe now that it has become more aesthetically pleasing.

**Review by robertodr — APPROVED** [review]

**Pull request merged**
