### PR TITLE
[WIP] Update libgetkw

### PR DESCRIPTION
**Pull request by stigrj**
Move to a more recent libgetkw with improved CMake setup. This removes some annoying compiler warnings on my laptop.

### CODE REVIEW

**Comment by stigrj** [comment]
Travis complains on the `Boost::boost` target. Any ideas?

**Comment by robertodr** [comment]
Boost is found but it seems the imported target `Boost::boost` isn't propagated from the `getkw` target to dependents (in this case the `cxx_test`) Can you try a serial build?

**Comment by robertodr** [comment]
I can't see anything that is obviously wrong. The set up is the exact same as used when compiling Getkw on its own (apart from `-DCMAKE_C_COMPILER` which is no longer needed).

**Comment by stigrj** [comment]
I get the same error on stallo, but not on my laptop

**Comment by robertodr** [comment]
I think the problem is that Getkw is a different project, hence its dependencies are not exported and transitively applied to MRChem. This will need work a little work Getkw-side. In the meantime you can search for Boost on your side, pass it down to Getkw (so the same version is used) and then list `Boost::boost` in `target_link_libraries` when you build the executable.

**Comment by robertodr** [comment]
Closing as it has been superseded by #119

**Pull request closed without merging**
