### PR TITLE
Disallow explicitly use of CMake user package registry

### LINKED ISSUE #232: building latest version
Hello,

I am trying to build the latest github version on several machines, and I am getting this error below.
Would you please give me hints what could be wrong ? I assume cmake is downloading and building dependencies "behind the scenes".

~~~
milias@lxir127.gsi.de:/tmp/milias-work/software/qch/mrchem_suite/mrchem_master/../setup --cxx=icpc build_icpccmake -DCMAKE_CXX_COMPILER=icpc -DEXTRA_CXXFLAGS="''" -DPYTHON_INTERPRETER="''" -DENABLE_MPI=False -DENABLE_OPENMP=False -DENABLE_CODE_COVERAGE=False -DCMAKE_BUILD_TYPE=release -G"Unix Makefiles" -H/tmp/milias-work/software/qch/mrchem_suite/mrchem_master -Bbuild_icpc

-- The CXX compiler identification is Intel 17.0.4.20170411
-- Check for working CXX compiler: /cvmfs/it.gsi.de/compiler/intel/17.0/compilers_and_libraries_2017.4.196/linux/bin/intel64/icpc
-- Check for working CXX compiler: /cvmfs/it.gsi.de/compiler/intel/17.0/compilers_and_libraries_2017.4.196/linux/bin/intel64/icpc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.9") 
-- Found Git: /usr/bin/git (found version "2.1.4") 
-- The C compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Suitable XCFun could not be located. Fetching and building!
-- Setting option ENABLE_CODE_COVERAGE: False
-- C++ compiler flags     :  -Wno-unknown-pragmas -g;-wd981;-wd279;-wd383;-wd1572;-wd177;-fno-rtti;-fno-exceptions  
-- C compiler flags       :  -ffloat-store;-m64  
-- Setting (unspecified) option STATIC_LIBRARY_ONLY: OFF
-- Setting (unspecified) option SHARED_LIBRARY_ONLY: OFF
-- Setting (unspecified) option ENABLE_GENERIC: OFF
-- Setting (unspecified) option XCFun_XC_MAX_ORDER: 3
-- Setting (unspecified) option PYMOD_INSTALL_LIBDIR: python
-- Setting (unspecified) option ENABLE_PYTHON_INTERFACE: OFF
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Setting (unspecified) option ENABLE_TESTALL: ON
-- Suitable Eigen3 could not be located. Fetching and building!
-- Performing Test EIGEN_COMPILER_SUPPORT_CPP11
-- Performing Test EIGEN_COMPILER_SUPPORT_CPP11 - Success
-- Performing Test COMPILER_SUPPORT_std=cpp03
-- Performing Test COMPILER_SUPPORT_std=cpp03 - Failed
-- Performing Test standard_math_library_linked_to_automatically
-- Performing Test standard_math_library_linked_to_automatically - Success
-- Standard libraries to link to explicitly: none
-- Performing Test COMPILER_SUPPORT_WERROR
-- Performing Test COMPILER_SUPPORT_WERROR - Success
-- Performing Test COMPILER_SUPPORT_pedantic
-- Performing Test COMPILER_SUPPORT_pedantic - Success
-- Performing Test COMPILER_SUPPORT_Wall
-- Performing Test COMPILER_SUPPORT_Wall - Success
-- Performing Test COMPILER_SUPPORT_Wextra
-- Performing Test COMPILER_SUPPORT_Wextra - Success
-- Performing Test COMPILER_SUPPORT_Wundef
-- Performing Test COMPILER_SUPPORT_Wundef - Success
-- Performing Test COMPILER_SUPPORT_Wcastalign
-- Performing Test COMPILER_SUPPORT_Wcastalign - Failed
-- Performing Test COMPILER_SUPPORT_Wcharsubscripts
-- Performing Test COMPILER_SUPPORT_Wcharsubscripts - Success
-- Performing Test COMPILER_SUPPORT_Wnonvirtualdtor
-- Performing Test COMPILER_SUPPORT_Wnonvirtualdtor - Success
-- Performing Test COMPILER_SUPPORT_Wunusedlocaltypedefs
-- Performing Test COMPILER_SUPPORT_Wunusedlocaltypedefs - Failed
-- Performing Test COMPILER_SUPPORT_Wpointerarith
-- Performing Test COMPILER_SUPPORT_Wpointerarith - Success
-- Performing Test COMPILER_SUPPORT_Wwritestrings
-- Performing Test COMPILER_SUPPORT_Wwritestrings - Success
-- Performing Test COMPILER_SUPPORT_Wformatsecurity
-- Performing Test COMPILER_SUPPORT_Wformatsecurity - Success
-- Performing Test COMPILER_SUPPORT_Wshorten64to32
-- Performing Test COMPILER_SUPPORT_Wshorten64to32 - Success
-- Performing Test COMPILER_SUPPORT_Wlogicalop
-- Performing Test COMPILER_SUPPORT_Wlogicalop - Failed
-- Performing Test COMPILER_SUPPORT_Wenumconversion
-- Performing Test COMPILER_SUPPORT_Wenumconversion - Failed
-- Performing Test COMPILER_SUPPORT_Wcpp11extensions
-- Performing Test COMPILER_SUPPORT_Wcpp11extensions - Failed
-- Performing Test COMPILER_SUPPORT_Wdoublepromotion
-- Performing Test COMPILER_SUPPORT_Wdoublepromotion - Failed
-- Performing Test COMPILER_SUPPORT_Wshadow
-- Performing Test COMPILER_SUPPORT_Wshadow - Success
-- Performing Test COMPILER_SUPPORT_Wnopsabi
-- Performing Test COMPILER_SUPPORT_Wnopsabi - Failed
-- Performing Test COMPILER_SUPPORT_Wnovariadicmacros
-- Performing Test COMPILER_SUPPORT_Wnovariadicmacros - Success
-- Performing Test COMPILER_SUPPORT_Wnolonglong
-- Performing Test COMPILER_SUPPORT_Wnolonglong - Success
-- Performing Test COMPILER_SUPPORT_fnochecknew
-- Performing Test COMPILER_SUPPORT_fnochecknew - Success
-- Performing Test COMPILER_SUPPORT_fnocommon
-- Performing Test COMPILER_SUPPORT_fnocommon - Success
-- Performing Test COMPILER_SUPPORT_fstrictaliasing
-- Performing Test COMPILER_SUPPORT_fstrictaliasing - Success
-- Performing Test COMPILER_SUPPORT_wd981
-- Performing Test COMPILER_SUPPORT_wd981 - Success
-- Performing Test COMPILER_SUPPORT_wd2304
-- Performing Test COMPILER_SUPPORT_wd2304 - Success
-- Performing Test COMPILER_SUPPORT_STRICTANSI
-- Performing Test COMPILER_SUPPORT_STRICTANSI - Success
-- Performing Test COMPILER_SUPPORT_Qunusedarguments
-- Performing Test COMPILER_SUPPORT_Qunusedarguments - Failed
-- Performing Test COMPILER_SUPPORT_OPENMP
-- Performing Test COMPILER_SUPPORT_OPENMP - Failed
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake-qt4 (found version "4.8.6") 
-- The Fortran compiler identification is GNU 4.9.2
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Found Qt4: /usr/bin/qmake-qt4 (found version "4.8.6") 
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so   
-- Found CHOLMOD: /usr/include/suitesparse  
-- Found UMFPACK: /usr/include/suitesparse  
-- Could NOT find SUPERLU (missing: SUPERLU_INCLUDES SUPERLU_LIBRARIES SUPERLU_VERSION_OK) 
-- A version of Pastix has been found but pastix_nompi.h does not exist in the include directory. Because Eigen tests require a version without MPI, we disable the Pastix backend.
-- 
-- Configured Eigen 3.3.7
-- 
-- Some things you can do now:
-- --------------+--------------------------------------------------------------
-- Command       |   Description
-- --------------+--------------------------------------------------------------
-- make install  | Install Eigen. Headers will be installed to:
--               |     <CMAKE_INSTALL_PREFIX>/<INCLUDE_INSTALL_DIR>
--               |   Using the following values:
--               |     CMAKE_INSTALL_PREFIX: /usr/local
--               |     INCLUDE_INSTALL_DIR:  include/eigen3
--               |   Change the install location of Eigen headers using:
--               |     cmake . -DCMAKE_INSTALL_PREFIX=yourprefix
--               |   Or:
--               |     cmake . -DINCLUDE_INSTALL_DIR=yourdir
-- make doc      | Generate the API documentation, requires Doxygen & LaTeX
-- make check    | Build and run the unit-tests. Read this page:
--               |   http://eigen.tuxfamily.org/index.php?title=Tests
-- make blas     | Build BLAS library (not the same thing as Eigen)
-- make uninstall| Removes files installed by make install
-- --------------+--------------------------------------------------------------
-- 
-- Suitable MRCPP could not be located. Fetching and building!
-- Setting (unspecified) option BUILD_STATIC_LIBS: OFF
-- Using Eigen3: /lustre/nyx/ukt/milias/work/software/mrchem_suite/mrchem (version 3.3.7)
-- Found packages:
 * PythonInterp
 * Qt4
 * OpenGL
 * Cholmod
 * Umfpack
 * Git

-- Suitable nlohmann_json could not be located: downloading and building nlohmann_json instead.
-- Using the single-header code from /tmp/milias-work/software/qch/mrchem_suite/mrchem_master/build_icpc/nlohmann_json_sources-src/single_include/
-- Found packages:
 * PythonInterp
 * Qt4
 * OpenGL
 * Cholmod
 * Umfpack
 * Git

-- Configuring incomplete, errors occurred!
See also "/tmp/milias-work/software/qch/mrchem_suite/mrchem_master/build_icpc/CMakeFiles/CMakeOutput.log".
See also "/tmp/milias-work/software/qch/mrchem_suite/mrchem_master/build_icpc/CMakeFiles/CMakeError.log".

CMake Error at /lustre/nyx/ukt/milias/work/software/mrchem_suite/mrchem/build_openmpi_intel17mkl/_deps/eigen3_sources-build/Eigen3Config.cmake:20 (include):
  include could not find load file:

    /lustre/nyx/ukt/milias/work/software/mrchem_suite/mrchem/build_openmpi_intel17mkl/_deps/eigen3_sources-build/Eigen3Targets.cmake
Call Stack (most recent call first):
  external/upstream/fetch_eigen3.cmake:1 (find_package)
  cmake/custom/main.cmake:10 (include)
  CMakeLists.txt:64 (include)


CMake Error at /lustre/nyx/ukt/milias/work/software/mrchem_suite/mrchem/build_openmpi_intel17mkl/_deps/eigen3_sources-build/Eigen3Config.cmake:20 (include):
  include could not find load file:

    /lustre/nyx/ukt/milias/work/software/mrchem_suite/mrchem/build_openmpi_intel17mkl/_deps/eigen3_sources-build/Eigen3Targets.cmake
Call Stack (most recent call first):
  build_icpc/mrcpp_sources-src/external/upstream/fetch_eigen3.cmake:3 (find_package)
  build_icpc/mrcpp_sources-src/cmake/custom/main.cmake:15 (include)
  build_icpc/mrcpp_sources-src/CMakeLists.txt:64 (include)
~~~

### PR DESCRIPTION
**Pull request by robertodr**
Fixes #232 @stigrj you should probably push a MRCPP v1.0.1 tag with the change in MRChemSoft/MRCPP#94 so we keep using tags, rather than commit hashes.

### CODE REVIEW

**Comment by robertodr** [comment]
Thanks for the tag.  I removed Eigen from my development environment and reproduced the issue. With the updated version of MRCPP and the proposed changes the issue is locally fixed. I'll remove installation of Eigen on Travis to double check.

**Comment by stigrj** [comment]
Great! Do we want to keep the Travis setup?

**Comment by robertodr** [comment]
I'd say yes. This bug was an error in overconfidence on my part which CI could have caught, if I had not optimized it's set up for speed... :man_facepalming:

**Comment by stigrj** [comment]
Ok, I will cherry-pick this to a version 0.2.1

**Pull request merged**
