### PR TITLE
Write RSP

### PR DESCRIPTION
**Pull request by stigrj**
Did a rebase on master and implemented reading of response orbitals. Had to make a new PR rather than push to ilfreddy due to the rebase...

### CODE REVIEW

**Comment by robertodr** [comment]
Suggestion: consider using https://github.com/rogersce/cnpy to write arrays to NumPy format. The files are cross-platform and can be loaded directly into Python. We've been using that library in PCMSolver and I wrote some [adapters for Eigen types](https://github.com/PCMSolver/pcmsolver/blob/master/src/utils/MathUtils.hpp#L359-L434) that you can reuse. Note that if you want to save to compressed NumPy format (basically a dictionary of NumPy arrays) you'll need to link against zlib.

**Comment by stigrj** [comment]
@robertodr any idea why CircleCI sometimes fails to launch the builds? The checks below just hangs with "Expecting", and the only way I've found to relaunch is to push something new

**Comment by robertodr** [comment]
No idea. Isn't there a restart button you can click in the web UI?

**Comment by stigrj** [comment]
Can't find one. The PR doesn't show up in CircleCI at all, not even the current successful build...

**Pull request merged**
