### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by stigrj**
Improvement:
- Slightly tighten the precision in the local algorithm for computing density and Coulomb potential. Relevant for MPI calculations without `numerically_exact = true`.

Bugfix:
- Fix orbital index in the file name when saving unrestricted orbitals

Bonus:
- Also threw in the `autocmake` update

### CODE REVIEW

**Comment by stigrj** [comment]
Or maybe the cmake thing needs to tested by @ilfreddy ?

**Comment by robertodr** [comment]
> Or maybe the cmake thing needs to tested by @ilfreddy ?

How does the `setup_command` file look with the latest changes in Autocmake?

**Comment by stigrj** [comment]
No quotes made it to the `setup_command`:
```
./setup --cmake-options=-DMRCPP_DIR=~/src/mrcpp/install-1.2.0a3/share/cmake/MRCPP
```

**Comment by robertodr** [comment]
> No quotes made it to the `setup_command`:
> 
> ```
> ./setup --cmake-options=-DMRCPP_DIR=~/src/mrcpp/install-1.2.0a3/share/cmake/MRCPP
> ```

I think the Autocmake fix only kicks in if you have more than one `-D` option in the list (with no spaces, quotes are irrelevant)

**Comment by stigrj** [comment]
Nifty
```
$ cat setup_command
./setup --cmake-options="-DMRCPP_DIR=~/src/mrcpp/install-1.2.0a3/share/cmake/MRCPP -DXCFun_DIR=~/src/xcfun/install-2.0.0a6/share/cmake/XCFun"
```

**Pull request merged**
