### PR TITLE
[WIP] Shared QM functions

### PR DESCRIPTION
**Pull request by gitpeterwind**
Shared memory for Coulomb density.
The present version is consistent, however it could be an advantage to set the "shared memory" into the density at a higher level: 
define a creator "Density(sharedmem)" corresponding to what we have in the FunctionTree.

### CODE REVIEW

**Comment by stigrj** [comment]
Great, I will continue the work on this branch and generalize the functionality into `QMFunction`. Hopefully I will finish before you leave for vacation.

**Comment by gitpeterwind** [comment]
What does this pr wait for? Is it ready to be merged?

**Comment by ilfreddy** [comment]
> What does this pr wait for? Is it ready to be merged?

Maybe you should consider removing the [WIP] label? :-)

**Comment by stigrj** [comment]
No, this one is not compatible with `master`, too many changes in `QMFunction`, `Density` etc. I have a generalization in https://github.com/stigrj/mrchem/tree/shared-mem that works with both shared densities and potentials, but it requires some final adjustments and testing.

**Comment by gitpeterwind** [comment]
ok, I hope that you can push it soon!

**Comment by stigrj** [comment]
Changes incorporated in #153

**Pull request closed without merging**
