### PR TITLE
Prepare MRChem-v1.1.1

### PR DESCRIPTION
**Pull request by stigrj**
Cherry-picks from `master`

### CODE REVIEW

**Review by robertodr — APPROVED** [review]
Looks good, but can we wait for the release? I want to fix the geometry optimization stuff with QCEngine plus write a notebook with examples for MRChem+QCEngine.

**Comment by stigrj** [comment]
Any ETA on the QCEngine stuff?

**Comment by robertodr** [comment]
Code-wise I'm done, but I'm still trying to get access to `sandel` to re-run my examples and write some documentation.

**Comment by stigrj** [comment]
Added a `squash` of #432, #433, #434

**Comment by robertodr** [comment]
Documentation for use with QCEngine finally done at #441

**Pull request merged**
