### PR TITLE
Improved MPI functionalities

### PR DESCRIPTION
**Pull request by stigrj**
Squashed the MPI part of Peter's PR #116.

Fixed the merge conflicts and the bug we discovered at the group meeting, and the code now runs successfully in parallel.

### CODE REVIEW

**Comment by stigrj** [comment]
@gitpeterwind can you run this version on some of your test cases and see if everything looks ok? Note that I have done *a lot* of meddling with the git history, so please don't try to merge back into some of your versions.

**Comment by robertodr** [comment]
@stigrj I put an embryo of MPI set up in `.circleci/config.yml`. It can be activated putting this stanza under `jobs`:
```yaml
  mpi-py3:
    <<: *ubuntu-1804
    environment:
      - PYTHON_VER: "3"
    steps:
      - checkout
      - *setup
      - *report
      - *configure-mpi
      - *build
      - *tests
```
and then ilsting it under the `workflows`. The tests will run serial though.

**Comment by gitpeterwind** [comment]
When I tried to compile it, I got this error:
``/home/mifapw/forkmrchem/mrchem/src/SCFDriver.cpp(9): catastrophic error: cannot open source file "getkw/Getkw.hpp"
  #include "getkw/Getkw.hpp"``
I might have an incomplete version of something. When/where was getkw/Getkw.hpp introduced?

**Comment by stigrj** [comment]
Then you have some old headers in the build directory. Try to do a `git submodule sync` and a new `./setup`

**Comment by gitpeterwind** [comment]
Thanks, that worked (although it made the older branch not work anymore).
The results are not identical (but the same within required precision). I think it is because in the squash-mpi the symmetrical treatment of the overlap matrix is not included.

**Comment by stigrj** [comment]
Is the symmetric overlap missing in this PR relative to your original?

**Comment by gitpeterwind** [comment]
yes, it is included in #116 but not in #123 (in qmfunctions.cpp)

**Comment by stigrj** [comment]
No, the symmetry is there, but in `orbital_utils.cpp`, and the `symmetric=true` is moved from `iter.next(true)` into the iterator constructor. This is because the symmetry property is not likely to change during an iteration procedure. Actually, I think I will move the `max_recv` parameter back into `next()` since this one could conceivably change. Also, I think I will move the symmetric iteration explicitly into `calc_overlap(Phi)` and let the `calc_overlap(Phi_a, Phi_b)` remain unsymmetric even if `Phi_a == Phi_b`.

**Comment by gitpeterwind** [comment]
Then I do not know what can cause the difference. Do you know other things that might have changed between the versions?

**Comment by stigrj** [comment]
I included the MPI build on CircleCI, but without the tests since there is no MPI initialization in the current test cases. However, it is nice to confirm that the code at least builds with MPI, even without the tests.

**Comment by stigrj** [comment]
I will do some more test calculations next week to convince myself that the current version is correct. Hopefully you don't have a lot of uncommitted changes on top of PR #116, @gitpeterwind . Otherwise we might have to manually import them.

**Comment by gitpeterwind** [comment]
The discrepancies between the  #116 and #123 were due to differences in the localization scheme: when the new scheme is included the results get identical.
The new localization scheme is not yet included in #123. It should be included later then (it scales better and use less memory).

**Pull request merged**
