### PR TITLE
Add alternative way of running MRChem in Betzy to docs

### PR DESCRIPTION
**Pull request by Gabrielgerez**
As @gitpeterwind has mentioned we could run in Betzy in a more general way, which is what i tried to show here in the docs.

### CODE REVIEW

**Comment by Gabrielgerez** [comment]
Note to everyone, i am not entirely sure of the options in the new command

**Comment by gitpeterwind** [comment]
Actually, the second "cyclic" , does not work exactly as I expected, so I still try to improve

**Comment by stigrj** [comment]
@gitpeterwind is this tested and ready?

**Comment by gitpeterwind** [comment]
> @gitpeterwind is this tested and ready?

The constant is tested (though not for h2o, which is a bit small), but not how it looks in the docs.

**Review by stigrj — APPROVED** [review]

**Pull request merged**
